nameOverride: "vmks"

grafana:
  admin:
    existingSecret: "grafana-admin-secret"
    userKey: admin-user
    passwordKey: admin-password

  grafana.ini:
    server:
      root_url: "https://grafana.golden-horde.ir"

  persistence:
    enabled: true
    type: pvc
    storageClassName: ""
    accessModes:
      - ReadWriteOnce
    size: 2Gi
    existingClaim: grafana-pvc