nameOverride: "vmks"


vmsingle:
  spec:
    storage:
      resources:
        requests:
          storage: 2Gi
    serviceSpec:
      spec:
        type: NodePort
        ports:
          - port: 8428
            nodePort: 32428
            
grafana:
  admin:
    existingSecret: "grafana-admin-secret"
    userKey: admin-user
    passwordKey: admin-password
  initChownData:
    enabled: false

  service:
    type: NodePort
    nodePort: 32000

  sidecar:
    dashboards:
      enabled: false
    datasources:
      enabled: false
      
  persistence:
    enabled: true
    type: pvc
    storageClassName: ""
    accessModes:
      - ReadWriteOnce
    size: 2Gi
    existingClaim: grafana-pvc

defaultDashboards:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true


vmalert:
  spec:
    serviceSpec:
      spec:
        type: NodePort
        ports:
          - port: 8080
            nodePort: 32080

vmagent:
  spec:
    serviceSpec:
      spec:
        type: NodePort
        ports:
          - port: 8429
            nodePort: 32429

alertmanager:
  spec:
    serviceSpec:
      spec:
        type: NodePort
        ports:
          - port: 9093
            nodePort: 32093