apiVersion: v1
kind: PersistentVolume
metadata:
  name: vmsingle-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /kubernetes-volumes/vmsingle
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: vmsingle-victoria-metrics-stack-vmks
    namespace: victoria-metrics-stack