apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/iman244/ctesiphon-k8s-gitops.git
    targetRevision: HEAD
    path: charts/cert-manager
    helm:
      valuesObject:
        crds:
          enabled: true
        tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
        featureGates: "ExperimentalGatewayAPISupport=true"
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true