apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: task-manager-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/iman244/ctesiphon-k8s-gitops.git
    targetRevision: HEAD
    path: charts/task-manager
    helm:
      valuesObject:
        namespace: task-manager-helm
        httproute:
          frontend:
            hostname: task-manager-helm.golden-horde.ir
          backend:
            hostname: task-manager-backend-helm.golden-horde.ir
  destination:
    server: https://kubernetes.default.svc
    namespace: task-manager-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true