apiVersion: v1
kind: Secret
metadata:
  name: task-manager-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.postgresUser }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword }}
  POSTGRES_DB: {{ .Values.secrets.postgresDb }}
  DATABASE_URL: postgresql+asyncpg://{{ .Values.secrets.postgresUser }}:{{ .Values.secrets.postgresPassword }}@postgres:{{ .Values.postgres.port }}/{{ .Values.secrets.postgresDb }}
  REDIS_URL: redis://redis:{{ .Values.redis.port }}/0