apiVersion: v1
kind: Secret
metadata:
  name: task-manager-secrets
  namespace: task-manager
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_DB: task_manager
  DATABASE_URL: postgresql+asyncpg://postgres:password@postgres:5432/task_manager
  REDIS_URL: redis://redis:6379/0