namespace: task-manager
backend:
  image:
    repository: iman244/task-manager-fastapi
    tag: v1.0.1
  port: 8000
  allowedOrigins: '["http://task-manager.golden-horde.ir"]'
  replicas: 1
frontend:
  image:
    repository: iman244/task-manager-nextjs
    tag: v1.0.2
  port: 3000
  apiUrl: http://backend:8000
  replicas: 1
postgres:
  image:
    repository: postgres
    tag: "18"
  port: 5432
  storage: 2Gi
  storageClassName: manual
  hostPath: /kubernetes/task-manager/postgres
  pgdata: /var/lib/postgresql/data/pgdata
redis:
  image:
    repository: redis
    tag: "8.8"
  port: 6379
secret:
  name: task-manager-secrets-external
gateway:
  name: traefik-gateway
  namespace: traefik
  sectionName: http
httproute:
  frontend:
    hostname: task-manager.golden-horde.ir
  backend:
    hostname: task-manager-backend.golden-horde.ir
